/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aplikasi_absensi_maven.gui;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;

import com.mycompany.aplikasi_absensi_maven.dao.*;
import com.mycompany.aplikasi_absensi_maven.entities.*;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.w3c.dom.UserDataHandler;
import com.itextpdf.layout.Document;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.element.Cell;
import com.mycompany.aplikasi_absensi_maven.db.DbConnection;
import com.mycompany.aplikasi_absensi_maven.gui.content.EditEmployee;
import com.mycompany.aplikasi_absensi_maven.gui.content.EditUser;
import com.mycompany.aplikasi_absensi_maven.gui.content.TambahAbsensi;
import com.mycompany.aplikasi_absensi_maven.gui.content.TambahEmployee;
import com.mycompany.aplikasi_absensi_maven.gui.content.TambahUser;
import java.io.FileNotFoundException;


public class Main extends javax.swing.JFrame {

    int totalUser = 0;
    int totalEmployee = 0;

    UserDAO userDao;
    EmployeeDAO employeeDAO;
    AttendanceDAO attendanceDAO;
    private DefaultTableModel userModel, employeeModel, attendanceModel;

    /**
     * Creates new form Main
     */
    public Main() {
        Connection con = DbConnection.connect();
        userDao = new UserDAO(con);
        employeeDAO = new EmployeeDAO(con);

        attendanceDAO = new AttendanceDAO(con);
        initComponents();
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateDateTime();
            }
        });
        timer.start();
        setLocationRelativeTo(null);
        initData();
    }

    public void initData() {
        totalUser = userDao.getTotalUsers();
        user_total.setText(String.valueOf(totalUser));
        totalEmployee = employeeDAO.getTotalEmployee();
        employe_total.setText(String.valueOf(totalEmployee));
        loadUserData();
        loadEmployees();
        loadAttendance();
    }

    public void move(JPanel panel) {
        content_panel.removeAll();
        content_panel.add(panel);
        content_panel.repaint();
        content_panel.revalidate();
    }

    private void loadUserData() {
        List<User> users = userDao.getAllUsers();
        userModel = new DefaultTableModel(new String[]{"ID", "Username", "Password", "Edit", "Delete"}, 0);
        users.forEach((t) -> {
            userModel.addRow(new Object[]{t.getId(), t.getUsername(), t.getPassword(), "Edit", "Delete"});
        });
        table_user.setModel(userModel);
    }

    private void loadEmployees() {
        var employees = employeeDAO.getAllEmployees();
        employeeModel = new DefaultTableModel(new String[]{"ID", "Name", "Position", "Edit", "Delete"}, 0);

        employees.forEach((t) -> {
            int id = t.getId();
            String name = t.getName();
            String position = t.getPosition();
            employeeModel.addRow(new Object[]{id, name, position, "Edit", "Delete"});
        });
        table_employee.setModel(employeeModel);
    }

    private void loadAttendance() {
        attendanceModel = new DefaultTableModel(new String[]{"ID", "Name", "Status", "Keterangan", "Waktu tanggal", "Delete"}, 0);

        List<Attendance> attendances = attendanceDAO.getAllAttendancesWithEmployeeName();
        attendances.forEach((t) -> {
            attendanceModel.addRow(new Object[]{t.getId(), t.getName(), t.getStatus(), t.getKeterangan(), t.getTimestamp(), "delete"});
        });
        table_attendance.setModel(attendanceModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        dateTimeLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dashboard_nav = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        user_nav = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        employee_nav = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        absensi_nav = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        content_panel = new javax.swing.JPanel();
        dashboard_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        user_total = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        employe_total = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        user_panel = new javax.swing.JPanel();
        tambah_user_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_user = new javax.swing.JTable();
        employee_panel = new javax.swing.JPanel();
        tambah_employee_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_employee = new javax.swing.JTable();
        absensi_panel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_attendance = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dateTimeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dateTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateTimeLabel.setText("Loading . . . ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(dateTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("Aplikasi Absensi");

        dashboard_nav.setBackground(new java.awt.Color(153, 204, 255));
        dashboard_nav.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        dashboard_nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboard_navMouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dashboard");

        javax.swing.GroupLayout dashboard_navLayout = new javax.swing.GroupLayout(dashboard_nav);
        dashboard_nav.setLayout(dashboard_navLayout);
        dashboard_navLayout.setHorizontalGroup(
            dashboard_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard_navLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboard_navLayout.setVerticalGroup(
            dashboard_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboard_navLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(10, 10, 10))
        );

        user_nav.setBackground(new java.awt.Color(153, 204, 255));
        user_nav.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        user_nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_navMouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User");
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout user_navLayout = new javax.swing.GroupLayout(user_nav);
        user_nav.setLayout(user_navLayout);
        user_navLayout.setHorizontalGroup(
            user_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_navLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        user_navLayout.setVerticalGroup(
            user_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_navLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(10, 10, 10))
        );

        employee_nav.setBackground(new java.awt.Color(153, 204, 255));
        employee_nav.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        employee_nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employee_navMouseClicked(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Employee");

        javax.swing.GroupLayout employee_navLayout = new javax.swing.GroupLayout(employee_nav);
        employee_nav.setLayout(employee_navLayout);
        employee_navLayout.setHorizontalGroup(
            employee_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_navLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        employee_navLayout.setVerticalGroup(
            employee_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employee_navLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(10, 10, 10))
        );

        absensi_nav.setBackground(new java.awt.Color(153, 204, 255));
        absensi_nav.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        absensi_nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                absensi_navMouseClicked(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Absensi");

        javax.swing.GroupLayout absensi_navLayout = new javax.swing.GroupLayout(absensi_nav);
        absensi_nav.setLayout(absensi_navLayout);
        absensi_navLayout.setHorizontalGroup(
            absensi_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(absensi_navLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        absensi_navLayout.setVerticalGroup(
            absensi_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, absensi_navLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dashboard_nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(user_nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(employee_nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(absensi_nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(dashboard_nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(user_nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employee_nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(absensi_nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content_panel.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total User");

        user_total.setForeground(new java.awt.Color(255, 255, 255));
        user_total.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_total, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(user_total)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total karyawan");

        employe_total.setForeground(new java.awt.Color(255, 255, 255));
        employe_total.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employe_total, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(employe_total)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Selamat datang admin diaplikasi absensi karyawan");

        javax.swing.GroupLayout dashboard_panelLayout = new javax.swing.GroupLayout(dashboard_panel);
        dashboard_panel.setLayout(dashboard_panelLayout);
        dashboard_panelLayout.setHorizontalGroup(
            dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboard_panelLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        dashboard_panelLayout.setVerticalGroup(
            dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard_panelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        content_panel.add(dashboard_panel, "card2");

        tambah_user_btn.setBackground(new java.awt.Color(0, 102, 255));
        tambah_user_btn.setForeground(new java.awt.Color(255, 255, 255));
        tambah_user_btn.setText("Tambah User");
        tambah_user_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_user_btnActionPerformed(evt);
            }
        });

        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_user);

        javax.swing.GroupLayout user_panelLayout = new javax.swing.GroupLayout(user_panel);
        user_panel.setLayout(user_panelLayout);
        user_panelLayout.setHorizontalGroup(
            user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(user_panelLayout.createSequentialGroup()
                        .addComponent(tambah_user_btn)
                        .addGap(0, 456, Short.MAX_VALUE)))
                .addContainerGap())
        );
        user_panelLayout.setVerticalGroup(
            user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tambah_user_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        content_panel.add(user_panel, "card3");

        tambah_employee_btn.setBackground(new java.awt.Color(0, 102, 255));
        tambah_employee_btn.setForeground(new java.awt.Color(255, 255, 255));
        tambah_employee_btn.setText("Tambah Pegawai");
        tambah_employee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_employee_btnActionPerformed(evt);
            }
        });

        table_employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_employeeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_employee);

        javax.swing.GroupLayout employee_panelLayout = new javax.swing.GroupLayout(employee_panel);
        employee_panel.setLayout(employee_panelLayout);
        employee_panelLayout.setHorizontalGroup(
            employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(employee_panelLayout.createSequentialGroup()
                        .addComponent(tambah_employee_btn)
                        .addGap(0, 435, Short.MAX_VALUE)))
                .addContainerGap())
        );
        employee_panelLayout.setVerticalGroup(
            employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tambah_employee_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        content_panel.add(employee_panel, "card4");

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Absen Pegawai");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 255, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Export CSV");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        table_attendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_attendanceMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_attendance);

        jButton4.setBackground(new java.awt.Color(255, 255, 0));
        jButton4.setText("Export PDF");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout absensi_panelLayout = new javax.swing.GroupLayout(absensi_panel);
        absensi_panel.setLayout(absensi_panelLayout);
        absensi_panelLayout.setHorizontalGroup(
            absensi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(absensi_panelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton2)
                .addGap(10, 10, 10)
                .addComponent(jButton3)
                .addGap(10, 10, 10)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(absensi_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
        absensi_panelLayout.setVerticalGroup(
            absensi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(absensi_panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(absensi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content_panel.add(absensi_panel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(content_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(content_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_navMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_navMouseClicked
        move(user_panel);
    }//GEN-LAST:event_user_navMouseClicked

    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed


    }//GEN-LAST:event_jLabel4KeyPressed

    private void dashboard_navMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_navMouseClicked
        // TODO add your handling code here:
        initData();
        move(dashboard_panel);
    }//GEN-LAST:event_dashboard_navMouseClicked

    private void employee_navMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employee_navMouseClicked
        // TODO add your handling code here:
        move(employee_panel);
    }//GEN-LAST:event_employee_navMouseClicked

    private void absensi_navMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absensi_navMouseClicked
        // TODO add your handling code here:
        move(absensi_panel);
    }//GEN-LAST:event_absensi_navMouseClicked

    private void tambah_user_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_user_btnActionPerformed
        // TODO add your handling code here:
        TambahUser tambahUser = new TambahUser(this, true, userDao);
        tambahUser.setVisible(true);
        loadUserData();
    }//GEN-LAST:event_tambah_user_btnActionPerformed

    private void table_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_userMouseClicked
        // TODO add your handling code here:
        int row = table_user.getSelectedRow();
        int col = table_user.getSelectedColumn();
        if (col == 3) { // Edit button clicked
            int userId = (int) userModel.getValueAt(row, 0);
            String username = (String) userModel.getValueAt(row, 1);
            String password = (String) userModel.getValueAt(row, 2);
            EditUser editUser = new EditUser(this, true, userDao, username, password, userId);
            editUser.setVisible(true);
            loadUserData();
        } else if (col == 4) { // Delete button clicked
            int userId = (int) userModel.getValueAt(row, 0);
            userDao.deleteUser(userId);
            loadUserData();
        }
    }//GEN-LAST:event_table_userMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        var isLogout = JOptionPane.showConfirmDialog(rootPane, "Apakah kamu yakin ingin keluar aplikasi");
        if (isLogout == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tambah_employee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_employee_btnActionPerformed
        // TODO add your handling code here:
        TambahEmployee tambahEmployee = new TambahEmployee(this, true, employeeDAO);
        tambahEmployee.setVisible(true);
        loadEmployees();
    }//GEN-LAST:event_tambah_employee_btnActionPerformed

    private void table_employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_employeeMouseClicked
        // TODO add your handling code here:
        int row = table_employee.getSelectedRow();
        int col = table_employee.getSelectedColumn();
        if (col == 3) { // Edit button clicked
            int userId = (int) employeeModel.getValueAt(row, 0);
            String username = (String) employeeModel.getValueAt(row, 1);
            String password = (String) employeeModel.getValueAt(row, 2);
            EditEmployee editEmployee = new EditEmployee(this, true, username, password, userId, employeeDAO);
            editEmployee.setVisible(true);
            loadEmployees();
        } else if (col == 4) { // Delete button clicked
            int userId = (int) employeeModel.getValueAt(row, 0);
            employeeDAO.deleteEmployee(userId);
            loadEmployees();
        }
    }//GEN-LAST:event_table_employeeMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TambahAbsensi absen = new TambahAbsensi(this, true, employeeDAO, attendanceDAO);
        absen.setVisible(true);
        loadAttendance();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            export("attendances.csv");
            JOptionPane.showMessageDialog(rootPane, "berhasil mengexport csv");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        generateReportPdf("absensi.pdf");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void table_attendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_attendanceMouseClicked
        // TODO add your handling code here:
        int row = table_attendance.getSelectedRow();
        int col = table_attendance.getSelectedColumn();
        int attendanceId = (int) attendanceModel.getValueAt(row, 0);
        var isDelete = attendanceDAO.deleteAttendance(attendanceId);
        if(isDelete){
            JOptionPane.showMessageDialog(rootPane, "Berhasil menghapus data absensi");
            loadAttendance();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Gagal menghapus data absensi");
        }
    }//GEN-LAST:event_table_attendanceMouseClicked

    private void updateDateTime() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date now = new Date();
        dateTimeLabel.setText(dateFormat.format(now));
    }

    public void export(String filePath) {
        List<Attendance> attendances = attendanceDAO.getAllAttendancesWithEmployeeName();
        try (FileWriter writer = new FileWriter(filePath)) {
            writer.append("Id , Employee name , Status , Keterangan, Tanggal dan waktu\n");
            attendances.forEach((t) -> {
                System.out.println(t.toString());
                try {
                    writer.append(String.valueOf(t.getId()) + ",");
                    writer.append(t.getName() + ",");
                    writer.append(t.getStatus() + ",");
                    writer.append(t.getKeterangan() + ",");
                    writer.append(t.getTimestamp() + "\n");
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            });
        } catch (IOException e) {
        }
    }

    public void generateReportPdf(String dest) {
        try {
            PdfWriter writer = new PdfWriter(dest);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);

            // Creating a table with 5 columns
            Table table = new Table(5);

//             Adding header cells
            table.addHeaderCell("ID");
            table.addHeaderCell("Employee Name");
            table.addHeaderCell("Status");
            table.addHeaderCell("Keterangan");
            table.addHeaderCell("Tanggal dan waktu");

            // Fetching attendance data
            List<Attendance> records = attendanceDAO.getAllAttendancesWithEmployeeName();

            // Adding data cells
            for (Attendance record : records) {
                table.addCell(String.valueOf(record.getId()));
                table.addCell(record.getName());
                table.addCell(record.getStatus());
                table.addCell(record.getKeterangan());
                table.addCell(record.getTimestamp());
            }

            // Adding table to the document
            document.add(table);

            // Closing the document
            document.close();
            JOptionPane.showMessageDialog(rootPane, "Berhasil generate pdf file");
            System.out.println("PDF report generated successfully.");
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel absensi_nav;
    private javax.swing.JPanel absensi_panel;
    private javax.swing.JPanel content_panel;
    private javax.swing.JPanel dashboard_nav;
    private javax.swing.JPanel dashboard_panel;
    private javax.swing.JLabel dateTimeLabel;
    private javax.swing.JLabel employe_total;
    private javax.swing.JPanel employee_nav;
    private javax.swing.JPanel employee_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_attendance;
    private javax.swing.JTable table_employee;
    private javax.swing.JTable table_user;
    private javax.swing.JButton tambah_employee_btn;
    private javax.swing.JButton tambah_user_btn;
    private javax.swing.JPanel user_nav;
    private javax.swing.JPanel user_panel;
    private javax.swing.JLabel user_total;
    // End of variables declaration//GEN-END:variables
}
